/* auto-generated: unversioned UND refs for load-time relocs */
void ERR_GenNewExternError(void){}
void ERR_GenNewFatalError(void){}
void ERR_InitErrorStatus(void){}
void ERR_IsError(void){}
void ERR_IsInternError(void){}
void GEOLIB_IsGeoringAbschnitt(void){}
void GEOLIB_IsIdentisch(void){}
void GEOLIB_IsStartpunkt(void){}
void GEOLIB_IsZielpunkt(void){}
void GEOLIB_laenge_von_bereich(void){}
void GEOLIB_xmax_in_abschnitt(void){}
void GEOLIB_xmin_element_in_bereich(void){}
void GEOLIB_xmin_in_abschnitt(void){}
void GEOLIB_xmin_in_bereich(void){}
void GEOLIB_ymax_in_abschnitt(void){}
void GEOLIB_ymin_in_abschnitt(void){}
void _Z10AEP_SetBamP6geotecS0_m(void){}
void _Z10mirr_punktPdS_ddd(void){}
void _Z10turn_punktPdS_ddd(void){}
void _Z11new_element9basvar_at(void){}
void _Z12break_geobasP5akopfPP6geotecdddd(void){}
void _Z12get_eckenartP6geotecS0_idd(void){}
void _Z13DeleteBereichP6geotecS0_(void){}
void _Z13GTFIND_IsLineP6geotec(void){}
void _Z13gen_bustreppev(void){}
void _Z13new_abschnitt7plan_at9gruppe_at9basvar_at(void){}
void _Z13trans_bereich8trans_atP5akopfP6geotecS3_dddd(void){}
void _Z14AEQ_SrkBereichPP6geotecS1_mi13eckenbearb_atddd(void){}
void _Z14connect_technoP6geotecS0_(void){}
void _Z14copy_abschnittP5akopfPS0_d(void){}
void _Z14delete_bereichP5akopfP6geotecS2_(void){}
void _Z15gen_lin_elementP6geotecddddPS0_dd(void){}
void _Z15gen_ringschlussP5akopfdd(void){}
void _Z15trans_abschnitt8trans_atP5akopfdddd(void){}
void _Z16AEP_IsTangentialP6geotecS0_idd(void){}
void _Z16AEP_SchnittCirHkP6geotecP5akopfdd(void){}
void _Z16AEP_schnittpunktP6geotecS0_PdS1_S1_S1_dd(void){}
void _Z16GTFIND_IsHorLineP6geotecdd(void){}
void _Z16GtDelete_KennungP5akopf12gt_status_atm(void){}
void _Z16delete_abschnittP5akopf(void){}
void _Z16invert_abschnittP5akopfd(void){}
void _Z16put_cir_komplettP6geotecddddddddd(void){}
void _Z16put_lin_komplettP6geotecddddddd(void){}
void _Z16separate_bereichP5akopfP6geotecS2_PS0_(void){}
void _Z16sp_kontur_konturP5akopfS0_PP10spkt_queueS3_dd(void){}
void _Z17GTFIND_IsVertLineP6geotecdd(void){}
void _Z17check_geo_bereichP6geotecS0_dd(void){}
void _Z17copy_geotec_datenP6geotecS0_(void){}
void _Z17delete_spkt_listePP10spkt_queue(void){}
void _Z18insert_bereich_vorP5akopfP6geotecS2_S2_(void){}
void _Z18korrigiere_elementP6geotecdd(void){}
void _Z18normiere_abschnittP5akopf6hsr_atidd(void){}
void _Z18sp_kreis_abschnittP5akopfdddPP6geotecPdS4_S4_S4_dd(void){}
void _Z19GtInsert_AddKennungP5akopf12gt_status_atm(void){}
void _Z19gen_lin_element_vorP5akopfP6geotecddhPS2_dd(void){}
void _Z20AEP_GenAnfahrElementP5akopfPP6geotec(void){}
void _Z20gen_lin_element_nachP5akopfP6geotecddhPS2_dd(void){}
void _Z20insert_abschnitt_vorP5akopfP6geotecPS0_d(void){}
void _Z20renormiere_abschnittP5akopf6hsr_atidd(void){}
void _Z20sp_element_abschnittP5akopfP6geotecPS2_PdS4_S4_S4_dd(void){}
void _Z21AEP_add_z_koordinatenP6geotecS0_(void){}
void _Z21GTFIND_IsAufDrehmitteP6geotecd(void){}
void _Z21sp_suchstrahl_elementdddP6geotecPdS1_hdd(void){}
void _Z22AEP_DeleteNullElementeP5akopfdd(void){}
void _Z22AEP_max_y_in_intervallP5akopfddddPddd(void){}
void _Z22CopyBereich_ohne_rucksP6geotecS0_PS0_S1_(void){}
void _Z22normiere_geo_abschnittP5akopfhdd(void){}
void _Z23sp_suchstrahl_abschnittdddP5akopfPdS1_hdd(void){}
void _Z25AEQ_OptimiereOffeneKonturPP5akopfmiddd(void){}
void _Z25copy_abschnitt_ohne_rucksP5akopfPS0_(void){}
void _Z26chk_punkt_innerhalb_konturP5akopfddPhdd(void){}
void _Z27CKK_delete_hinterschneidungPP5akopfdddd(void){}
void _Z27chk_punkt_ausserhalb_konturP5akopfddPhdd(void){}
void _Z27teile_element_auf_drehmitteP5akopfcdd(void){}
void _Z30unterteile_kreise_in_abschnittP5akopfdd(void){}
void _Z31CKK_SetStartpunktNachLinksUntenP5akopfdd(void){}
void _Z34delete_grenzkontur_vor_huellkonturP5akopfS0_dd(void){}
void _Z41delete_grenzkontur_ausserhalb_huellkonturP5akopfS0_dd(void){}
void _Z6spechtP6geotecS0_PdS1_S1_S1_dd(void){}
void _Z9AEP_xwertdP6geotecd(void){}
void _Z9AEP_ywertdP6geotecd(void){}
void _ZN6nckern9codecheck12RegistrationC1ENS0_7SegmentESt17basic_string_viewIcSt11char_traitsIcEE(void){}
void _ZN6nckern9codecheck12RegistrationD1Ev(void){}
void abstand_pkt_kontur(void){}
void abstand_pkt_pkt(void){}
void cir_length(void){}
void compare_winkel(void){}
void element_length(void){}
void kurzpunkt_kontur(void){}
void lin_length(void){}
void lotpunkt_cir(void){}
void mpt_cbpw(void){}
void norm_winkel(void){}
void oeffnungswinkel(void){}
void pt_distance_arclength(void){}
void punkt_auf_kontur(void){}
void punkt_auf_konturelement(void){}
void punktlage(void){}
void ringschluss(void){}
void sp_linw_linw(void){}
void steigungswinkel(void){}
void tangenten_winkel(void){}
void tangentenwinkel_in_sektorenwinkel(void){}
void tp_mpw(void){}
void w_linpt_cir(void){}
void wert_im_intervall(void){}
void wert_im_offenen_intervall(void){}
void winkel_im_sektor(void){}
void winkelhalbierende(void){}
