/* auto-generated: unversioned UND refs for load-time relocs */
void ERR_GenNewExternError(void){}
void ERR_GenNewExternWarning(void){}
void ERR_GenNewFatalError(void){}
void ERR_GenNewInternError(void){}
void ERR_InitErrorStatus(void){}
void ERR_IsExternWarning(void){}
void ERR_IsInternError(void){}
void ERR_IsSystemError(void){}
void ERR_IsWarning(void){}
void GEOLIB_GetWinkelRichtung(void){}
void GEOLIB_IsGeoringAbschnitt(void){}
void GEOLIB_IsIdentisch(void){}
void GEOLIB_IsMathIdentisch(void){}
void GEOLIB_IsStartpunkt(void){}
void GEOLIB_IsZielpunkt(void){}
void GEOLIB_LinMittelpunkt(void){}
void GEOLIB_bogenlaenge_aus_endpunkten(void){}
void GEOLIB_laenge_von_bereich(void){}
void GEOLIB_scheitelpunkt(void){}
void GEOLIB_xmax_in_abschnitt(void){}
void GEOLIB_xmin_in_abschnitt(void){}
void GEOLIB_ymax_in_abschnitt(void){}
void GEOLIB_ymin_element_in_abschnitt(void){}
void GEOLIB_ymin_in_abschnitt(void){}
void GEOLIB_ymin_in_bereich(void){}
void WZNORM_GetWerkzeugOrientierung(void){}
void WerkzeugTyp(void){}
void _Z10AEP_SetBamP6geotecS0_m(void){}
void _Z11ANF_tec_vorP6geotech(void){}
void _Z11CopyBereichP6geotecS0_PS0_S1_(void){}
void _Z11CopyElementP6geotec(void){}
void _Z11GTLIB_IsOddi(void){}
void _Z11delete_restP5akopf(void){}
void _Z11delete_spktPP10spkt_queueS1_S1_(void){}
void _Z11ini_elementP6geotec9basvar_at(void){}
void _Z11knotenpunktP6geotecS0_dd(void){}
void _Z11new_element9basvar_at(void){}
void _Z11separate_gkPP11konturlisteS1_S0_(void){}
void _Z11suche_xwertPddP6geotecS1_d(void){}
void _Z11suche_ywertdPdP6geotecS1_d(void){}
void _Z12GTFIND_IsCycP6geotec(void){}
void _Z12GTLIB_IsEveni(void){}
void _Z12InvertKonturPP6geotecS1_d(void){}
void _Z12break_geobasP5akopfPP6geotecdddd(void){}
void _Z12copy_bereichP5akopfP6geotecS2_PS0_d(void){}
void _Z12get_eckenartP6geotecS0_idd(void){}
void _Z13DeleteBereichP6geotecS0_(void){}
void _Z13GTFIND_IsCircP6geotec(void){}
void _Z13GTFIND_IsLineP6geotec(void){}
void _Z13dealloc_akopfP5akopf(void){}
void _Z13new_abschnitt7plan_at9gruppe_at9basvar_at(void){}
void _Z13set_stech_parP13tec_grvuni_rtP6geotecP15konturkorrektur(void){}
void _Z13trans_bereich8trans_atP5akopfP6geotecS3_dddd(void){}
void _Z13trans_element8trans_atP5akopfP6geotecdddd(void){}
void _Z14AEP_SetBamNullP5akopfdd(void){}
void _Z14AEP_set_ovsi_0P6geotec(void){}
void _Z14ANF_AnfahrG830P13tec_cycuni_rtP5akopfS2_S2_6hsr_atcddddd(void){}
void _Z14ANF_AnfahrG835P13tec_cycuni_rtP5akopfS2_S2_6hsr_atcddddd(void){}
void _Z14copy_abschnittP5akopfPS0_d(void){}
void _Z14dealloc_geotecP6geotec(void){}
void _Z14delete_bereichP5akopfP6geotecS2_(void){}
void _Z14free_kk_recordP15konturkorrektur(void){}
void _Z14insert_gk_nachPP11konturlisteS0_S0_(void){}
void _Z14invert_bereichPP6geotecS1_d(void){}
void _Z14normiere_punktPdS_6hsr_atid(void){}
void _Z14separate_gk_lxPP11konturlisteS1_S0_(void){}
void _Z15AEP_VorschubTypP6geotec(void){}
void _Z15ANF_AbfahrKontpP13tec_cycuni_rtP5akopfS2_S2_dddi(void){}
void _Z15ANF_AnfahrAchspP13tec_cycuni_rtP5akopfddddddPS2_(void){}
void _Z15delete_gk_listePP11konturliste(void){}
void _Z15gen_ringschlussP5akopfdd(void){}
void _Z15konturkorrekturP15konturkorrektur(void){}
void _Z15korrigiere_lineP6geotecdd(void){}
void _Z15set_abstech_parP6geotecS0_P15konturkorrektur(void){}
void _Z15set_schrupp_parP13tec_cycuni_rtP6geotecP15konturkorrektur(void){}
void _Z15trans_abschnitt8trans_atP5akopfdddd(void){}
void _Z16AEQ_SrkAbschnittPP5akopfmi11srk_lage_at13eckenbearb_atddd(void){}
void _Z16GTFIND_IsHorLineP6geotecdd(void){}
void _Z16GtDelete_KennungP5akopf12gt_status_atm(void){}
void _Z16GtDelete_KennungP6geotecS0_12gt_status_atm(void){}
void _Z16delete_abschnittP5akopf(void){}
void _Z16invert_abschnittP5akopfd(void){}
void _Z16korrigiere_kreisP6geotecdd(void){}
void _Z16put_lin_komplettP6geotecddddddd(void){}
void _Z16renormiere_punktPdS_6hsr_ati(void){}
void _Z16separate_bereichP5akopfP6geotecS2_PS0_(void){}
void _Z16set_schlicht_parP13tec_cyckon_rtP6geotecP15konturkorrektur(void){}
void _Z16sp_kontur_konturP5akopfS0_PP10spkt_queueS3_dd(void){}
void _Z16test_geomerkmaleP6geotecS0_d(void){}
void _Z17CKK_compute_unionRP5akopfS1_dd(void){}
void _Z17GTFIND_IsVertLineP6geotecdd(void){}
void _Z17GtVerwalt_SetNcsaP5akopft(void){}
void _Z17GtVerwalt_SetNcseP5akopft(void){}
void _Z17InsertElementNachP6geotecS0_(void){}
void _Z17check_cir_elementcP6geotecdd(void){}
void _Z17check_geo_bereichP6geotecS0_dd(void){}
void _Z17copy_geotec_datenP6geotecS0_(void){}
void _Z17delete_spkt_listePP10spkt_queue(void){}
void _Z17get_grundelementecP6geotecPS0_S1_(void){}
void _Z17insert_akopf_nachP5akopfS0_(void){}
void _Z17set_formstech_parP6geotecS0_P15konturkorrektur(void){}
void _Z17set_freistech_parP10mp_frei_rtP6geotecP15konturkorrektur(void){}
void _Z17set_stechdreh_parP12tec_iscar_rtP6geotecP15konturkorrektur(void){}
void _Z18AEQ_GenHuellkonturP5akopfiddPS0_dd(void){}
void _Z18ANF_iscar_anschrupiP15konturkorrekturddddP5akopfS2_dPdS3_Ph(void){}
void _Z18delete_geomerkmaleP5akopf(void){}
void _Z18delete_nc_rucksackP5akopfP6geotec(void){}
void _Z18korrigiere_elementP6geotecdd(void){}
void _Z18normiere_abschnittP5akopf6hsr_atidd(void){}
void _Z18renormiere_bereichP6geotecS0_6hsr_atid(void){}
void _Z18set_simschrupp_parP14tec_simschruppP6geotecP15konturkorrektur(void){}
void _Z19GtInsert_AddKennungP5akopf12gt_status_atm(void){}
void _Z19GtInsert_SetKennungP5akopf12gt_status_atm(void){}
void _Z19gen_lin_element_vorP5akopfP6geotecddhPS2_dd(void){}
void _Z19insert_bereich_nachP5akopfP6geotecS2_S2_(void){}
void _Z19separate_gk_bereichPP11konturlisteS1_S0_S0_(void){}
void _Z19set_simschlicht_parP10tec_simkonP6geotecP15konturkorrektur(void){}
void _Z20AEP_shift_startpunktP5akopfddd(void){}
void _Z20AEQ_AufmassAbschnittPP5akopfmihdddd(void){}
void _Z20ANF_AbfahrSchlichtenP9anfahr_rtd(void){}
void _Z20ANF_AnfahrSchlichtenP9anfahr_rtd6hsr_atcddd(void){}
void _Z20CKK_anfahrbegrenzungP15konturkorrekturP5akopf(void){}
void _Z20CKK_get_rohteil_lagehP6geotecS0_S0_S0_dddddd(void){}
void _Z20elimin_ineck_verrundP15konturkorrekturd(void){}
void _Z20gen_lin_element_nachP5akopfP6geotecddhPS2_dd(void){}
void _Z20insert_abschnitt_vorP5akopfP6geotecPS0_d(void){}
void _Z20normiere_geo_bereichP5akopfPP6geotecS3_hdd(void){}
void _Z20renormiere_abschnittP5akopf6hsr_atidd(void){}
void _Z20set_gewinde_din_paraP6geotecdsPiS1_Pd(void){}
void _Z20suche_rohteilbereichPP6geotecS1_ddddd(void){}
void _Z21ANF_achsp_anfahrpunktP15konturkorrekturP5akopfdP8uq_achspdPdS5_Ph(void){}
void _Z21CKK_breiten_korrekturP5akopfdPhdd(void){}
void _Z21GTFIND_IsHorLineAchseP6geotecdd(void){}
void _Z21insert_abschnitt_nachP5akopfP6geotecPS0_d(void){}
void _Z21rohnach_fuer_kontkorrP5akopfS0_dd(void){}
void _Z22AEPLIB_GetCycleContourP12cyc_basis_rtPP6geotecS3_(void){}
void _Z22AEP_max_y_in_intervallP5akopfddddPddd(void){}
void _Z22CKK_PrepareSimschlichtP15konturkorrektur(void){}
void _Z22CKK_kontur_unterteilenihPP5akopfS1_PP11konturlisteS4_Phdd(void){}
void _Z22CKK_korr_auf_drehmittePP5akopfdd(void){}
void _Z22CopyBereich_ohne_rucksP6geotecS0_PS0_S1_(void){}
void _Z22GTDELETE_ElementAmEndeP5akopf12gt_status_atm(void){}
void _Z22delete_abschnitt_linksPP5akopfddd(void){}
void _Z22insert_gk_bereich_nachPP11konturlisteS1_S0_S0_S0_(void){}
void _Z22normiere_geo_abschnittP5akopfhdd(void){}
void _Z22normiere_geo_abschnittPP5akopfhdd(void){}
void _Z22set_startpunkt_in_xminP5akopfdd(void){}
void _Z23AEP_GenCirElementAmEndeP5akopf10aufmass_rtdidd(void){}
void _Z23delete_abschnitt_rechtsPP5akopfddd(void){}
void _Z23sp_suchstrahl_abschnittdddP5akopfPdS1_hdd(void){}
void _Z24CKK_GenNormiertesRohteilP15konturkorrekturPP5akopf(void){}
void _Z24GTDELETE_ElementAmAnfangP5akopf12gt_status_atm(void){}
void _Z24schnittbegrenzung_laengsP5akopfS0_7sbgr_atddd(void){}
void _Z24sp_halbgerade_halbgeradeddddddPdS_dd(void){}
void _Z25AEP_GenCirElementAmAnfangP5akopf10aufmass_rtdidd(void){}
void _Z25AEP_divide_abschnitt_in_xP5akopfddd(void){}
void _Z25SIMCYC_SetFkt_addkorr_ausPFvP6geotecP17NCBlockBufferTypeE(void){}
void _Z25SIMCYC_SetFkt_addkorr_einPFvP6geotecP17NCBlockBufferTypeE(void){}
void _Z25break_rt_in_gk_endpunktenP5akopfS0_dd(void){}
void _Z25delete_kontur_in_gk_listeP11konturliste(void){}
void _Z26CKK_last_fallendes_elementP6geotecS0_12monotonie_atdd(void){}
void _Z26SIMCYC_SetFkt_simkont_ncbbPFvP6geotecdhP17NCBlockBufferTypeE(void){}
void _Z26chk_punkt_innerhalb_konturP5akopfddPhdd(void){}
void _Z26hole_din_werte_freistich_gdPP16din_freistich_rt(void){}
void _Z27AEP_divide_abschnitt_in_lngP5akopfdddd(void){}
void _Z27AEP_teile_element_in_xmitteP5akopfPP6geotecdd(void){}
void _Z27CKK_delete_hinterschneidungPP5akopfdddd(void){}
void _Z27CKK_first_fallendes_elementP6geotecdd(void){}
void _Z27CKK_verlaengere_konturendenP5akopfS0_6hsr_atcddd(void){}
void _Z27chk_punkt_ausserhalb_konturP5akopfddPhdd(void){}
void _Z27delete_bearbeitungsmerkmaleP5akopfd(void){}
void _Z27hole_din_werte_freistich_efdPP16din_freistich_rt(void){}
void _Z27konturdrehsinn_in_abschnittP5akopfdd(void){}
void _Z27teile_element_auf_drehmitteP5akopfcdd(void){}
void _Z28CKK_prepare_hinterschneidungP5akopfddd(void){}
void _Z29CKK_korr_schlicht_stechkonturP5akopfddd(void){}
void _Z30CKK_GenSimschlichtAnfahrWinkelP5akopfS0_dddbidPddd(void){}
void _Z30CKK_gk_bereiche_zusammenfassenP11konturlistePS0_P5akopfdd(void){}
void _Z30GTFIND_BereichKennungImCalstatP5akopfmPP6geotecS3_(void){}
void _Z30GTFIND_BereichKennungImTmpstatP5akopfmPP6geotecS3_(void){}
void _Z30unterteile_kreise_in_abschnittP5akopfdd(void){}
void _Z31insert_akopf_nach_am_listenendeP5akopfS0_(void){}
void _Z32CKK_GenSimschlichtFinkonturUnionP15konturkorrekturPP5akopf(void){}
void _Z32SIMCYC_SetFkt_store_toolpositionPFvddE(void){}
void _Z32sp_suchstrahl_verletzt_abschnittdddP5akopfPdS1_Phdd(void){}
void _Z33CKK_set_kontur_oberhalb_drehachseP5akopfdd(void){}
void _Z34CKK_delete_bereich_aus_konturlistePP11konturlisteS1_S1_PP6geotecS4_S4_S4_(void){}
void _Z38CKK_GenSimschlichtFinkonturVerlaengernP15konturkorrektur(void){}
void _Z41CKK_delete_grenzkontur_ausserhalb_rohteilihP5akopfPP11konturlisteS3_Phdd(void){}
void _Z41CKK_restore_werkzeugdaten_schruppen_4achshP6geotecP15konturkorrektur(void){}
void _Z41delete_grenzkontur_ausserhalb_huellkonturP5akopfS0_dd(void){}
void _Z42CKK_loesche_rohteil_ausserhalb_grenzkonturP11konturlistedd(void){}
void _Z6new_gkPP11konturlisteS1_(void){}
void _Z6spechtP6geotecS0_PdS1_S1_S1_dd(void){}
void _Z8CheckGeoP5akopfhdd(void){}
void _Z9AEP_xwertdP6geotecd(void){}
void _Z9AEP_ywertdP6geotecd(void){}
void _Z9delete_gkPP11konturlisteS1_S0_(void){}
void _Z9new_akopf7plan_at9gruppe_at(void){}
void _Z9new_gk_llP11konturlistePS0_(void){}
void _ZN16SimTurnInterface16run_finish_cycleEP10tec_simkonP6geotecddRP5akopfS6_bP17NCBlockBufferTypebS5_(void){}
void _ZN16SimTurnInterface17run_schrupp_cycleEP14tec_simschruppP6geotecddRP5akopfS6_bP17NCBlockBufferTypebS5_(void){}
void _ZN6nckern9codecheck12RegistrationC1ENS0_7SegmentESt17basic_string_viewIcSt11char_traitsIcEE(void){}
void _ZN6nckern9codecheck12RegistrationD1Ev(void){}
void _ZN9ProductId16IsTurningProductEv(void){}
void abstand_pkt_kontur(void){}
void abstand_pkt_pkt(void){}
void abstand_start_ziel(void){}
void abstand_ziel_start(void){}
void compare_winkel(void){}
void kurzpunkt_kontur(void){}
void lin_length(void){}
void mpt_start_ziel(void){}
void norm_winkel(void){}
void normiere_winkel(void){}
void oeffnungswinkel(void){}
void punkt_auf_kontur(void){}
void punkt_auf_konturelement(void){}
void punktlage(void){}
void ringschluss(void){}
void sign(void){}
void sp_lin_lin(void){}
void sp_linw_cir(void){}
void sp_linw_linw(void){}
void steigungswinkel(void){}
void stg_element(void){}
void tangenten_winkel(void){}
void tp_mpw(void){}
void wert_im_intervall(void){}
void winkel_im_sektor(void){}
void winkelhalbierende(void){}
