/* auto-generated: unversioned UND refs for load-time relocs */
void ERR_GenNewExternError(void){}
void ERR_GenNewExternWarning(void){}
void ERR_GenNewFatalError(void){}
void ERR_GenNewInternError(void){}
void ERR_InitErrorStatus(void){}
void ERR_IsError(void){}
void ERR_IsInternError(void){}
void ERR_IsSystemError(void){}
void ERR_IsUserError(void){}
void ERR_IsWarning(void){}
void GEOLIB_IsStartpunkt(void){}
void GEOLIB_IsZielpunkt(void){}
void GEOLIB_winkel_lng_dx(void){}
void GEOLIB_winkel_lng_dy(void){}
void _Z10gen_konturPP5akopf7plan_at9gruppe_ati(void){}
void _Z10turn_punktPdS_ddd(void){}
void _Z11delete_restP5akopf(void){}
void _Z11ini_elementP6geotec9basvar_at(void){}
void _Z11new_element9basvar_at(void){}
void _Z12copy_bereichP5akopfP6geotecS2_PS0_d(void){}
void _Z12form_elementP6geotecm(void){}
void _Z13DeleteBereichP6geotecS0_(void){}
void _Z13GTFIND_IsLineP6geotec(void){}
void _Z13dealloc_akopfP5akopf(void){}
void _Z13new_abschnitt7plan_at9gruppe_at9basvar_at(void){}
void _Z14connect_technoP6geotecS0_(void){}
void _Z14connect_ueblagP6geotecS0_S0_(void){}
void _Z14copy_abschnittP5akopfPS0_d(void){}
void _Z14dealloc_geotecP6geotec(void){}
void _Z14delete_bereichP5akopfP6geotecS2_(void){}
void _Z15gen_end_elementP5akopf9basvar_at(void){}
void _Z15gen_ringschlussP5akopfdd(void){}
void _Z15kontur_lsg_testcP5akopfdd(void){}
void _Z15trans_abschnitt8trans_atP5akopfdddd(void){}
void _Z16GTFIND_IsBohrungP6geotec(void){}
void _Z16GTFIND_IsHorLineP6geotecdd(void){}
void _Z16GTFIND_WholeLineP5akopfP6geotecPS2_S3_d(void){}
void _Z16delete_abschnittP5akopf(void){}
void _Z16gen_element_nachP5akopfP6geotec9basvar_atPS2_(void){}
void _Z16invert_abschnittP5akopfd(void){}
void _Z16put_lin_komplettP6geotecddddddd(void){}
void _Z16separate_bereichP5akopfP6geotecS2_PS0_(void){}
void _Z16set_schnittpunktP6geotecS0_dddd(void){}
void _Z17GTFIND_IsEinstichP6geotec(void){}
void _Z17GTFIND_IsVarianteP6geotec9basvar_at(void){}
void _Z17GTFIND_IsVertLineP6geotecdd(void){}
void _Z17chk_input_cir_mptP6geotecd(void){}
void _Z17copy_geotec_datenP6geotecS0_(void){}
void _Z17disconnect_technoP6geotec(void){}
void _Z17disconnect_ueblagP6geotec(void){}
void _Z17get_grundelementecP6geotecPS0_S1_(void){}
void _Z17insert_akopf_nachP5akopfS0_(void){}
void _Z18CalcFreistichDatenP6geotecS0_S0_dd(void){}
void _Z18chk_input_cir_zielP6geotecd(void){}
void _Z18delete_ub_rucksackP5akopfP6geotec(void){}
void _Z18insert_element_vorP5akopfP6geotecS2_(void){}
void _Z19GtInsert_AddKennungP6geotec12gt_status_atm(void){}
void _Z19chk_input_cir_startP6geotecd(void){}
void _Z19get_nf_grundelementcP6geotecPS0_(void){}
void _Z19get_vg_grundelementcP6geotecPS0_(void){}
void _Z19insert_element_nachP5akopfP6geotecS2_(void){}
void _Z19ueberlagern_bohrungP5akopfS0_dd(void){}
void _Z20GTFIND_IsGeoKomplettP6geotec(void){}
void _Z20chk_input_lin_winkelcP6geotecS0_dd(void){}
void _Z20disconnect_abschnittP5akopf(void){}
void _Z20schnittpunkt_cir_cirP6geotecS0_PiPdS2_S2_S2_d(void){}
void _Z20schnittpunkt_cir_linP6geotecS0_PiPdS2_S2_S2_dd(void){}
void _Z20schnittpunkt_lin_cirP6geotecS0_PiPdS2_S2_S2_dd(void){}
void _Z20schnittpunkt_lin_linP6geotecS0_PiPdS2_dd(void){}
void _Z20ueberlagern_einstichP5akopfS0_PP6geotecS3_dd(void){}
void _Z21insert_abschnitt_nachP5akopfP6geotecPS0_d(void){}
void _Z21sp_suchstrahl_bereichdddP6geotecS0_PdS1_hdd(void){}
void _Z21ueberlagern_freistichP5akopfS0_PP6geotecS3_dd(void){}
void _Z22CreateAndConnectGeotecP5akopfP6geotec9basvar_at(void){}
void _Z23AEP_GetEinstichRefpunktP6geotecS0_PdS1_dd(void){}
void _Z23aufloes_form_in_bereichP5akopfP6geotecS2_(void){}
void _Z24chk_input_cir_zielwinkelP6geotecS0_dd(void){}
void _Z25chk_input_cir_startwinkelP6geotecdd(void){}
void _Z27konturdrehsinn_in_abschnittP5akopfdd(void){}
void _Z29AEP_ChkKnotenpunktInAbschnittP5akopfdd(void){}
void _Z8CheckGeoP5akopfhdd(void){}
void _ZN6nckern9codecheck12RegistrationC1ENS0_7SegmentESt17basic_string_viewIcSt11char_traitsIcEE(void){}
void _ZN6nckern9codecheck12RegistrationD1Ev(void){}
void abstand_pkt_gerade(void){}
void abstand_pkt_pkt(void){}
void cir_length(void){}
void compare_winkel(void){}
void lin_length(void){}
void lng_cart_in_xy(void){}
void lng_winkel_in_xy(void){}
void lng_winkelinkr_in_xy(void){}
void lnginkr_winkel_in_xy(void){}
void mpt_cmp_tan_c_tan_cmp(void){}
void mpt_cmp_tan_c_tan_lzpw(void){}
void mpt_cmp_tan_cbp(void){}
void mpt_cmp_tan_cmpx(void){}
void mpt_cmp_tan_cmpy(void){}
void mpt_lgpw_tan_c_tan_lgpw(void){}
void mpt_lgpw_tan_cbp(void){}
void mpt_lgpw_tan_cmpx(void){}
void mpt_lgpw_tan_cmpy(void){}
void mpt_start_ziel(void){}
void norm_winkel(void){}
void normiere_winkel(void){}
void punktlage(void){}
void ringschluss(void){}
void sektorenwinkel_in_tangentenwinkel(void){}
void sign(void){}
void sp_cir_cir(void){}
void sp_lin_cir(void){}
void sp_linw_cir(void){}
void sp_linw_linw(void){}
void steigungswinkel(void){}
void tangenten_winkel(void){}
void tangentenwinkel_clc(void){}
void tp_cir_cir(void){}
void tp_mpw(void){}
void w_linpt_cir(void){}
void winkel_x_in_xy(void){}
void winkel_y_in_xy(void){}
void x_cir_koord(void){}
void x_lin_koord(void){}
void y_cir_koord(void){}
void y_lin_koord(void){}
