/* auto-generated: unversioned UND refs for load-time relocs */
void ERRPLIB_NewSysWarning(void){}
void ERRPLIB_SetFileAndLine(void){}
void ERR_GenNewExternError(void){}
void ERR_GenNewFatalError(void){}
void ERR_GenNewInternError(void){}
void ERR_GenSystemWarning(void){}
void ERR_InitErrorStatus(void){}
void ERR_IsExternError(void){}
void ERR_IsInternError(void){}
void ERR_IsSystemError(void){}
void ERR_IsWarning(void){}
void GEOLIB_IsGeoringAbschnitt(void){}
void GEOLIB_IsMathIdentisch(void){}
void GEOLIB_IsMathInvers(void){}
void GEOLIB_IsStartpunkt(void){}
void GEOLIB_IsZielpunkt(void){}
void GEOLIB_LinMittelpunkt(void){}
void GEOLIB_bogenlaenge_aus_endpunkten(void){}
void GEOLIB_extrema_in_abschnitt(void){}
void GEOLIB_laenge_von_abschnitt(void){}
void GEOLIB_laenge_von_bereich(void){}
void GEOLIB_select_far_point(void){}
void GEOLIB_select_next_point(void){}
void GEOLIB_xmax_element_in_abschnitt(void){}
void GEOLIB_xmax_in_abschnitt(void){}
void GEOLIB_xmin_element_in_abschnitt(void){}
void GEOLIB_xmin_in_abschnitt(void){}
void GEOLIB_ymin_element_in_abschnitt(void){}
void GEOLIB_ymin_in_abschnitt(void){}
void _Z10AEP_DelBamP6geotecS0_m(void){}
void _Z10AEP_SetBamP6geotecS0_m(void){}
void _Z10gen_konturPP5akopf7plan_at9gruppe_ati(void){}
void _Z10sp_min_maxP6geotecddPdS1_S1_S1_dd(void){}
void _Z11delete_restP5akopf(void){}
void _Z11delete_spktPP10spkt_queueS1_S1_(void){}
void _Z11elemin_formP5akopfmddddd(void){}
void _Z11knotenpunktP6geotecS0_dd(void){}
void _Z11new_element9basvar_at(void){}
void _Z12GTFIND_IsCycP6geotec(void){}
void _Z12break_geobasP5akopfPP6geotecdddd(void){}
void _Z12copy_bereichP5akopfP6geotecS2_PS0_d(void){}
void _Z12get_eckenartP6geotecS0_idd(void){}
void _Z13DeleteBereichP6geotecS0_(void){}
void _Z13GTFIND_IsCircP6geotec(void){}
void _Z13GTFIND_IsLineP6geotec(void){}
void _Z13trans_element8trans_atP5akopfP6geotecdddd(void){}
void _Z14FFLIB_GenFigurP6geotecd7plan_at9gruppe_atdddddtPP5akopfdd(void){}
void _Z14GTFIND_IsCirCWP6geotec(void){}
void _Z14GTFIND_KennungP5akopf12gt_status_atm(void){}
void _Z14chk_zustellungP6geotec(void){}
void _Z14copy_abschnittP5akopfPS0_d(void){}
void _Z14delete_bereichP5akopfP6geotecS2_(void){}
void _Z14invert_bereichPP6geotecS1_d(void){}
void _Z15GTFIND_IsCirCCWP6geotec(void){}
void _Z15gen_ringschlussP5akopfdd(void){}
void _Z15kont_schl_drehsP5akopfdd(void){}
void _Z15korrigiere_lineP6geotecdd(void){}
void _Z15trans_abschnitt8trans_atP5akopfdddd(void){}
void _Z16AEP_schnittpunktP6geotecS0_PdS1_S1_S1_dd(void){}
void _Z16GTFIND_IsHorLineP6geotecdd(void){}
void _Z16GtDelete_KennungP6geotecS0_12gt_status_atm(void){}
void _Z16InsertElementVorP6geotecS0_(void){}
void _Z16delete_abschnittP5akopf(void){}
void _Z16get_ueberlappungP6geotecS0_PiPdS2_S2_S2_dd(void){}
void _Z16insert_akopf_lowP5akopfS0_(void){}
void _Z16insert_akopf_vorP5akopfS0_(void){}
void _Z16invert_abschnittP5akopfd(void){}
void _Z16korrigiere_kreisP6geotecdd(void){}
void _Z16new_schnittpunkt12spkt_lage_atddP6geotecS1_S1_S1_PP10spkt_queueS4_dd(void){}
void _Z16put_cir_komplettP6geotecddddddddd(void){}
void _Z16put_lin_komplettP6geotecddddddd(void){}
void _Z16put_rnd_komplettP6geotecS0_S0_ddddddddd(void){}
void _Z16schliesse_lueckeP6geotecS0_dd(void){}
void _Z16schnittpunktlageddP6geotecS0_dd(void){}
void _Z16separate_bereichP5akopfP6geotecS2_PS0_(void){}
void _Z16set_schnittpunktP6geotecS0_dddd(void){}
void _Z16sp_kontur_konturP5akopfS0_PP10spkt_queueS3_dd(void){}
void _Z17GTFIND_IsVertLineP6geotecdd(void){}
void _Z17GtVerwalt_SetNcsaP5akopft(void){}
void _Z17GtVerwalt_SetNcseP5akopft(void){}
void _Z17check_geo_bereichP6geotecS0_dd(void){}
void _Z17delete_spkt_listePP10spkt_queue(void){}
void _Z17insert_akopf_nachP5akopfS0_(void){}
void _Z18check_null_elementP6geotecdd(void){}
void _Z18korrigiere_elementP6geotecdd(void){}
void _Z18sp_element_bereichP6geotecS0_S0_PS0_PdS2_S2_S2_dd(void){}
void _Z19GEO_BerechneRundungP6geotecS0_S0_dd(void){}
void _Z19GtInsert_AddKennungP6geotec12gt_status_atm(void){}
void _Z19flaeche_von_bereichP6geotecS0_dd(void){}
void _Z19gen_lin_element_vorP5akopfP6geotecddhPS2_dd(void){}
void _Z19insert_element_nachP5akopfP6geotecS2_(void){}
void _Z20AEP_SetEintauchXPlusP5akopfdd(void){}
void _Z20AEP_SetEintauchZPlusP5akopfdd(void){}
void _Z20AEP_shift_startpunktP5akopfddd(void){}
void _Z20disconnect_abschnittP5akopf(void){}
void _Z20gen_lin_element_nachP5akopfP6geotecddhPS2_dd(void){}
void _Z20insert_abschnitt_vorP5akopfP6geotecPS0_d(void){}
void _Z20normiere_geo_bereichP5akopfPP6geotecS3_hdd(void){}
void _Z20schnittpunkt_lin_linP6geotecS0_PiPdS2_dd(void){}
void _Z20sp_element_abschnittP5akopfP6geotecPS2_PdS4_S4_S4_dd(void){}
void _Z21AEP_SetEintauchXMinusP5akopfdd(void){}
void _Z21AEP_SetEintauchZMinusP5akopfdd(void){}
void _Z22CopyBereich_ohne_rucksP6geotecS0_PS0_S1_(void){}
void _Z22normiere_geo_abschnittP5akopfhdd(void){}
void _Z22normiere_geo_abschnittPP5akopfhdd(void){}
void _Z22schnittbegrenzung_planP5akopfS0_7sbgr_atddd(void){}
void _Z23abstand_element_elementP6geotecS0_dd(void){}
void _Z23sp_suchstrahl_abschnittdddP5akopfPdS1_hdd(void){}
void _Z25aufloes_form_in_abschnittP5akopf(void){}
void _Z25break_abschnitt_abschnittP5akopfS0_dd(void){}
void _Z25first_akopf_in_hierarchieP5akopf(void){}
void _Z25test_bearbeitungsmerkmaleP5akopfP6geotecS2_d(void){}
void _Z26chk_punkt_innerhalb_konturP5akopfddPhdd(void){}
void _Z27chk_punkt_ausserhalb_konturP5akopfddPhdd(void){}
void _Z27konturdrehsinn_in_abschnittP5akopfdd(void){}
void _Z29AEP_ChkKnotenpunktInAbschnittP5akopfdd(void){}
void _Z29gen_ringschluss_in_hierarchieP5akopfdd(void){}
void _Z30unterteile_kreise_in_abschnittP5akopfdd(void){}
void _Z31insert_akopf_nach_am_listenendeP5akopfS0_(void){}
void _Z33AEP_SetInnenAussenStirnRueckseiteP5akopfdd(void){}
void _Z5dichtP6geotecS0_d(void){}
void _Z6spechtP6geotecS0_PdS1_S1_S1_dd(void){}
void _Z8CheckGeoP5akopfhdd(void){}
void _Z8cirtolinP6geotecdd(void){}
void _Z9AEP_ywertdP6geotecd(void){}
void _Z9new_akopf7plan_at9gruppe_at(void){}
void _ZN6nckern9codecheck12RegistrationC1ENS0_7SegmentESt17basic_string_viewIcSt11char_traitsIcEE(void){}
void _ZN6nckern9codecheck12RegistrationD1Ev(void){}
void abstand_pkt_bogen(void){}
void abstand_pkt_pkt(void){}
void abstand_pkt_strecke(void){}
void abstand_start_ziel(void){}
void abstand_ziel_start(void){}
void cir_length(void){}
void compare_winkel(void){}
void element_im_kreis(void){}
void element_length(void){}
void flaeche_von_dreieck(void){}
void flaeche_von_segment(void){}
void flaeche_von_sektor(void){}
void lin_length(void){}
void norm_winkel(void){}
void oeffnungswinkel(void){}
void punkt_auf_konturelement(void){}
void punktlage(void){}
void ringschluss(void){}
void sign(void){}
void sp_linw_cir(void){}
void sp_linw_linw(void){}
void steigungswinkel(void){}
void tangenten_winkel(void){}
void tangentenwinkel_clc(void){}
void tp_mpw(void){}
void winkel_im_sektor(void){}
void winkelhalbierende(void){}
