/* auto-generated: unversioned UND refs for load-time relocs */
void ERRPLIB_NewSysWarning(void){}
void ERRPLIB_SetFileAndLine(void){}
void ERR_GenNewExternError(void){}
void ERR_GenNewFatalError(void){}
void ERR_InitErrorStatus(void){}
void ERR_IsInternError(void){}
void GEOLIB_IsBeruehrpunkt(void){}
void GEOLIB_IsGeoringAbschnitt(void){}
void GEOLIB_LinMittelpunkt(void){}
void GEOLIB_bogenlaenge_aus_oeffnungswinkel(void){}
void GEOLIB_scheitelpunkt(void){}
void WZNORM_GetWerkzeugGruppe(void){}
void WerkzeugTyp(void){}
void _Z10AEQ_PocketPP5akopfi10aufmass_rtdddd(void){}
void _Z10gen_konturPP5akopf7plan_at9gruppe_ati(void){}
void _Z11CopyElementP6geotec(void){}
void _Z11delete_restP5akopf(void){}
void _Z11delete_spktPP10spkt_queueS1_S1_(void){}
void _Z11new_element9basvar_at(void){}
void _Z12break_geobasP5akopfPP6geotecdddd(void){}
void _Z12get_eckenartP6geotecS0_idd(void){}
void _Z13DeleteBereichP6geotecS0_(void){}
void _Z13GTFIND_IsCircP6geotec(void){}
void _Z13GTFIND_IsLineP6geotec(void){}
void _Z13dealloc_akopfP5akopf(void){}
void _Z13new_abschnitt7plan_at9gruppe_at9basvar_at(void){}
void _Z14FFLIB_GenFigurP6geotecd7plan_at9gruppe_atdddddtPP5akopfdd(void){}
void _Z14GTFIND_IsFigurP5akopf(void){}
void _Z14GTFIND_KennungP5akopf12gt_status_atm(void){}
void _Z14copy_abschnittP5akopfPS0_d(void){}
void _Z14delete_bereichP5akopfP6geotecS2_(void){}
void _Z14invert_elementP6geotecd(void){}
void _Z15AEQ_FraesKonturPP5akopfmi11srk_lage_at10aufmass_rtddd(void){}
void _Z15ANF_AbfahrFraesP6geotecP5akopfS2_S2_c(void){}
void _Z15ANF_AnfahrFraesP6geotecS0_P5akopfS2_S2_c(void){}
void _Z15GTFIND_IsMusterP5akopf(void){}
void _Z15GTFIND_IsTascheP5akopf(void){}
void _Z15gen_end_elementP5akopf9basvar_at(void){}
void _Z15gen_ringschlussP5akopfdd(void){}
void _Z15trans_abschnitt8trans_atP5akopfdddd(void){}
void _Z16AEP_IsAusseneckeP6geotecS0_idd(void){}
void _Z16AEP_SchnittCirHkP6geotecP5akopfdd(void){}
void _Z16AEQ_SrkAbschnittPP5akopfmi11srk_lage_at13eckenbearb_atddd(void){}
void _Z16GTFIND_IsAbflachP5akopf(void){}
void _Z16GtDelete_KennungP5akopf12gt_status_atm(void){}
void _Z16delete_abschnittP5akopf(void){}
void _Z16find_first_akopf7plan_at9gruppe_at(void){}
void _Z16gen_element_nachP5akopfP6geotec9basvar_atPS2_(void){}
void _Z16insert_akopf_lowP5akopfS0_(void){}
void _Z16invert_abschnittP5akopfd(void){}
void _Z16put_cir_komplettP6geotecddddddddd(void){}
void _Z16put_lin_komplettP6geotecddddddd(void){}
void _Z16separate_bereichP5akopfP6geotecS2_PS0_(void){}
void _Z16set_schnittpunktP6geotecS0_dddd(void){}
void _Z16sp_kontur_konturP5akopfS0_PP10spkt_queueS3_dd(void){}
void _Z17ANF_GetHelixInnenP5akopfS0_PdS1_Phdd(void){}
void _Z17GEO_BerechneFigurP5akopfdd(void){}
void _Z17GTFIND_IsMehrkantP5akopf(void){}
void _Z17delete_spkt_listePP10spkt_queue(void){}
void _Z17insert_akopf_nachP5akopfS0_(void){}
void _Z18ANF_GetHelixAussenP6geotecP5akopfS2_PdS3_Ph(void){}
void _Z18insert_element_vorP5akopfP6geotecS2_(void){}
void _Z18korrigiere_elementP6geotecdd(void){}
void _Z19GtInsert_AddKennungP5akopf12gt_status_atm(void){}
void _Z19chk_element_im_ringP6geotec(void){}
void _Z19insert_bereich_nachP5akopfP6geotecS2_S2_(void){}
void _Z19insert_element_nachP5akopfP6geotecS2_(void){}
void _Z20AEQ_AufmassAbschnittPP5akopfmihdddd(void){}
void _Z20GTFIND_IstNameGleichPKcS0_(void){}
void _Z20disconnect_abschnittP5akopf(void){}
void _Z20schnittpunkt_lin_linP6geotecS0_PiPdS2_dd(void){}
void _Z20sp_halbgerade_konturddddP6geotecS0_PdS1_hdd(void){}
void _Z21AEP_GenTanBogenAmEndeP5akopfddd(void){}
void _Z21insert_abschnitt_nachP5akopfP6geotecPS0_d(void){}
void _Z22AEQ_GetLaengentoleranzdd(void){}
void _Z22ANF_GetVorbohrungInnenP6geotecP5akopfS2_PdS3_Ph(void){}
void _Z22CopyBereich_ohne_rucksP6geotecS0_PS0_S1_(void){}
void _Z22normiere_geo_abschnittP5akopfhdd(void){}
void _Z23AEP_GenLinElementAmEndeP5akopfddhPP6geotecdd(void){}
void _Z23AEP_GenTanBogenAmAnfangP5akopfddd(void){}
void _Z23ANF_GetVorbohrungAussenP6geotecP5akopfS2_PdS3_Ph(void){}
void _Z23GTFIND_Anfahrpositionen9gruppe_ath(void){}
void _Z23sp_suchstrahl_abschnittdddP5akopfPdS1_hdd(void){}
void _Z24CKK_Flaechenkorrektur_XYP5akopfdPhdd(void){}
void _Z24CKK_Flaechenkorrektur_YZP5akopfddddd(void){}
void _Z24GEO_GetRundungVorzeichenP6geotecS0_Pddd(void){}
void _Z25AEP_GenLinElementAmAnfangP5akopfddhPP6geotecdd(void){}
void _Z25aufloes_form_in_abschnittP5akopf(void){}
void _Z25insert_akopf_on_top_levelP5akopf(void){}
void _Z26chk_punkt_innerhalb_konturP5akopfddPhdd(void){}
void _Z27ANF_GetVorbohrungG840AussenP6geotecP5akopfS2_dPdS3_Ph(void){}
void _Z27chk_punkt_ausserhalb_konturP5akopfddPhdd(void){}
void _Z27konturdrehsinn_in_abschnittP5akopfdd(void){}
void _Z29GTCONNECT_DisconnectAbschnittPP5akopfS1_S0_(void){}
void _Z30unterteile_kreise_in_abschnittP5akopfdd(void){}
void _Z31insert_akopf_nach_am_listenendeP5akopfS0_(void){}
void _Z8CheckGeoP5akopfhdd(void){}
void _Z9new_akopf7plan_at9gruppe_at(void){}
void _ZN6nckern9codecheck12RegistrationC1ENS0_7SegmentESt17basic_string_viewIcSt11char_traitsIcEE(void){}
void _ZN6nckern9codecheck12RegistrationD1Ev(void){}
void abstand_pkt_kontur(void){}
void abstand_pkt_pkt(void){}
void cir_length(void){}
void compare_winkel(void){}
void lin_length(void){}
void lotpunkt_lin(void){}
void mpt_bptw_lgpw(void){}
void mpt_cbpw(void){}
void mpt_cmp_tan_c_tan_lzpw(void){}
void mpt_lgpw_bptw(void){}
void mpt_rp_zptw(void){}
void mpt_rptw_zp(void){}
void norm_winkel(void){}
void oeffnungswinkel(void){}
void pt_distance_arclength(void){}
void ringschluss(void){}
void sektorenwinkel_in_tangentenwinkel(void){}
void sign(void){}
void sp_linw_linw(void){}
void steigungswinkel(void){}
void tangenten_winkel(void){}
void tangentenwinkel_clc(void){}
void tangentenwinkel_in_sektorenwinkel(void){}
void tp_cir_cir(void){}
void tp_mpw(void){}
void w_linpt_cir(void){}
