/* auto-generated: define every unversioned UND symbol so the
   trimmed real .so satisfies its load-time data relocations. */
void GetZtPoi(void){}
void ZT_getResolution(void){}
void _ZN10FMetaValueC2Ev(void){}
void _ZN10FMetaValueD2Ev(void){}
void _ZN11BasicStringIcED2Ev(void){}
void _ZN11CfgMailslot7GetDataEjRK7astringR8GMessage(void){}
void _ZN15CfgJhProtectionC1Ev(void){}
void _ZN15CfgJhProtectionD1Ev(void){}
void _ZN15CfgJhProtectionptEv(void){}
void _ZN21ForceLinkGMESSAGEMISCC1Ev(void){}
void _ZN21ForceLinkGMESSAGEMISCD1Ev(void){}
void _ZN6OptionC1ENS_11GEnumOptionE(void){}
void _ZN6nckern9codecheck12RegistrationC1ENS0_7SegmentESt17basic_string_viewIcSt11char_traitsIcEE(void){}
void _ZN6nckern9codecheck12RegistrationD1Ev(void){}
void _ZN8GMsgEnumD2Ev(void){}
void _ZN9MetaValue11theRealImplE(void){}
void _ZN9MetaValue11theSignImplE(void){}
void _ZN9MetaValue12theDummyImplE(void){}
void _ZN9MetaValue14theIntegerImplE(void){}
void _ZN9MetaValue15theCardinalImplE(void){}
void _ZN9MetaValue19MaxFractionalDigitsEPKcS1_S1_S1_(void){}
void _ZNK10FMetaValue6ToTextB5cxx11EPKvjNS_4UnitEb(void){}
void _ZNK8GMsgEnum11LiteralNameEi(void){}
void _ZNK9MetaValue12CardinalImpl10CheckRangeEPKcS2_St17basic_string_viewIcSt11char_traitsIcEES6_(void){}
void _ZNK9MetaValue12CardinalImpl10IsCardinalEv(void){}
void _ZNK9MetaValue12CardinalImpl13GetMemorySizeEv(void){}
void _ZNK9MetaValue12CardinalImpl18EducatedCheckRangeEPKcS2_St17basic_string_viewIcSt11char_traitsIcEES6_(void){}
void _ZNK9MetaValue12CardinalImpl6ToTextEPKvjPcS3_PKNS_6FormatE(void){}
void _ZNK9MetaValue12CardinalImpl8ToBinaryEPKcS2_Pvj(void){}
void _ZNK9MetaValue4Impl6IsRealEv(void){}
void _ZNK9MetaValue4Impl9IsIntegerEv(void){}
void _ZNK9MetaValue8RealImpl11CheckSyntaxEPKcS2_j(void){}
void _ZNK9MetaValue8RealImpl13GetMemorySizeEv(void){}
void _ZNK9MetaValue8RealImpl18EducatedCheckRangeEPKcS2_St17basic_string_viewIcSt11char_traitsIcEES6_(void){}
void _ZNK9MetaValue8RealImpl6ToTextEPKvjPcS3_PKNS_6FormatE(void){}
void _ZNK9MetaValue8RealImpl8ToBinaryEPKcS2_Pvj(void){}
void _ZTI10FMetaValue(void){}
void _ZTIN9MetaValue12CardinalImplE(void){}
void _ZTV6Option(void){}
void _ZTV9CfgResult(void){}
void _ZTVN9MetaValue12CardinalImplE(void){}
void tstrDigits(void){}
void tstrType(void){}
