/* auto-generated: unversioned UND refs for load-time relocs */
void ERR_GenNewExternError(void){}
void ERR_GenNewExternErrorTextArg(void){}
void ERR_GenNewExternWarning(void){}
void ERR_GenNewFatalError(void){}
void ERR_GenNewInternError(void){}
void ERR_InitErrorStatus(void){}
void ERR_IsExternWarning(void){}
void ERR_IsInternError(void){}
void ERR_IsSystemError(void){}
void GEOLIB_GetWinkelRichtung(void){}
void GEOLIB_IsGeoringAbschnitt(void){}
void GEOLIB_IsIdentisch(void){}
void GEOLIB_IsInvers(void){}
void GEOLIB_IsInversParallel(void){}
void GEOLIB_IsMathInvers(void){}
void GEOLIB_IsStartpunkt(void){}
void GEOLIB_IsZielpunkt(void){}
void GEOLIB_bogenlaenge_aus_endpunkten(void){}
void GEOLIB_extrema_in_abschnitt(void){}
void GEOLIB_scheitelpunkt(void){}
void GEOLIB_xmax_element_in_abschnitt(void){}
void GEOLIB_xmax_in_abschnitt(void){}
void GEOLIB_xmin_in_abschnitt(void){}
void GEOLIB_ymax_in_abschnitt(void){}
void GEOLIB_ymax_in_bereich(void){}
void GEOLIB_ymin_element_in_abschnitt(void){}
void GEOLIB_ymin_in_abschnitt(void){}
void GEOLIB_ymin_in_bereich(void){}
void WZNORM_GetWerkzeugIk(void){}
void WZNORM_GetWerkzeugOrientierung(void){}
void WZ_GetWzLageIcpSchlichten(void){}
void WZ_GetWzLageIcpSchruppen(void){}
void WZ_GetWzLageIcpStechen(void){}
void WZ_HsrLaengs(void){}
void WZ_HsrPlan(void){}
void WZ_IcpBeaRichtung(void){}
void WerkzeugTyp(void){}
void _Z10AEP_DelBamP6geotecS0_m(void){}
void _Z10AEP_SetBamP6geotecS0_m(void){}
void _Z10gen_konturPP5akopf7plan_at9gruppe_ati(void){}
void _Z11GTLIB_IsOddi(void){}
void _Z11delete_restP5akopf(void){}
void _Z11elemin_formP5akopfmddddd(void){}
void _Z11new_element9basvar_at(void){}
void _Z12GTFIND_IsCycP6geotec(void){}
void _Z12GTLIB_IsEveni(void){}
void _Z12break_geobasP5akopfPP6geotecdddd(void){}
void _Z12copy_bereichP5akopfP6geotecS2_PS0_d(void){}
void _Z12get_eckenartP6geotecS0_idd(void){}
void _Z13GTFIND_IsCircP6geotec(void){}
void _Z13GTFIND_IsLineP6geotec(void){}
void _Z13dealloc_akopfP5akopf(void){}
void _Z13new_abschnitt7plan_at9gruppe_at9basvar_at(void){}
void _Z13trans_bereich8trans_atP5akopfP6geotecS3_dddd(void){}
void _Z14AEP_SetBamNullP5akopfdd(void){}
void _Z14AEP_set_ovsi_0P6geotec(void){}
void _Z14GTFIND_KennungP5akopf12gt_status_atm(void){}
void _Z14GTFIND_KennungP6geotecS0_12gt_status_atm(void){}
void _Z14copy_abschnittP5akopfPS0_d(void){}
void _Z14delete_bereichP5akopfP6geotecS2_(void){}
void _Z15AEP_IsInneneckeP6geotecS0_idd(void){}
void _Z15AEP_VorschubTypP6geotec(void){}
void _Z15GTFIND_IsMusterP5akopf(void){}
void _Z15gen_lin_elementP6geotecddddPS0_dd(void){}
void _Z15gen_ringschlussP5akopfdd(void){}
void _Z15kont_schl_drehsP5akopfdd(void){}
void _Z15korrigiere_lineP6geotecdd(void){}
void _Z15trans_abschnitt8trans_atP5akopfdddd(void){}
void _Z16AEP_IsAusseneckeP6geotecS0_idd(void){}
void _Z16AEQ_SrkAbschnittPP5akopfmi11srk_lage_at13eckenbearb_atddd(void){}
void _Z16GTFIND_IsAbflachP5akopf(void){}
void _Z16GTFIND_IsHorLineP6geotecdd(void){}
void _Z16GtDelete_KennungP5akopf12gt_status_atm(void){}
void _Z16GtDelete_KennungP6geotec12gt_status_atm(void){}
void _Z16GtDelete_KennungP6geotecS0_12gt_status_atm(void){}
void _Z16delete_abschnittP5akopf(void){}
void _Z16find_first_akopf7plan_at9gruppe_at(void){}
void _Z16invert_abschnittP5akopfd(void){}
void _Z16korrigiere_kreisP6geotecdd(void){}
void _Z16put_cir_komplettP6geotecddddddddd(void){}
void _Z16put_lin_komplettP6geotecddddddd(void){}
void _Z16separate_bereichP5akopfP6geotecS2_PS0_(void){}
void _Z16set_schnittpunktP6geotecS0_dddd(void){}
void _Z16sp_kontur_konturP5akopfS0_PP10spkt_queueS3_dd(void){}
void _Z16spiegele_bereichP6geotecS0_(void){}
void _Z17GTFIND_IsMehrkantP5akopf(void){}
void _Z17GTFIND_IsVertLineP6geotecdd(void){}
void _Z17GtVerwalt_SetNcsaP5akopft(void){}
void _Z17GtVerwalt_SetNcseP5akopft(void){}
void _Z17copy_geotec_datenP6geotecS0_(void){}
void _Z17delete_spkt_listePP10spkt_queue(void){}
void _Z18GEO_BerechneKonturP5akopfdd(void){}
void _Z18GTFIND_AnzElementeP5akopf(void){}
void _Z18delete_nc_rucksackP5akopfP6geotec(void){}
void _Z18insert_bereich_vorP5akopfP6geotecS2_S2_(void){}
void _Z18insert_element_vorP5akopfP6geotecS2_(void){}
void _Z18korrigiere_elementP6geotecdd(void){}
void _Z19GtInsert_AddKennungP5akopf12gt_status_atm(void){}
void _Z19GtInsert_AddKennungP6geotec12gt_status_atm(void){}
void _Z19GtInsert_AddKennungP6geotecS0_12gt_status_atm(void){}
void _Z19GtInsert_SetKennungP5akopf12gt_status_atm(void){}
void _Z19flaeche_von_bereichP6geotecS0_dd(void){}
void _Z19gen_lin_element_vorP5akopfP6geotecddhPS2_dd(void){}
void _Z19insert_bereich_nachP5akopfP6geotecS2_S2_(void){}
void _Z19insert_element_nachP5akopfP6geotecS2_(void){}
void _Z19set_ghalt_satzweiseP6geotecS0_(void){}
void _Z20AEP_SetEintauchXPlusP5akopfdd(void){}
void _Z20AEP_SetEintauchZPlusP5akopfdd(void){}
void _Z20AEQ_AufmassAbschnittPP5akopfmihdddd(void){}
void _Z20GTFIND_ChkStatusBitsP6geotec12gt_status_atm(void){}
void _Z20gen_lin_element_nachP5akopfP6geotecddhPS2_dd(void){}
void _Z20insert_abschnitt_vorP5akopfP6geotecPS0_d(void){}
void _Z20suche_rohteilbereichPP6geotecS1_ddddd(void){}
void _Z21AEP_SetEintauchXMinusP5akopfdd(void){}
void _Z21AEP_SetEintauchZMinusP5akopfdd(void){}
void _Z21GTFIND_IsHorLineAchseP6geotecdd(void){}
void _Z21insert_abschnitt_nachP5akopfP6geotecPS0_d(void){}
void _Z21rohnach_fuer_kontkorrP5akopfS0_dd(void){}
void _Z21sp_suchstrahl_bereichdddP6geotecS0_PdS1_hdd(void){}
void _Z21sp_suchstrahl_elementdddP6geotecPdS1_hdd(void){}
void _Z22CopyBereich_ohne_rucksP6geotecS0_PS0_S1_(void){}
void _Z22GTDELETE_ElementAmEndeP5akopf12gt_status_atm(void){}
void _Z22normiere_geo_abschnittP5akopfhdd(void){}
void _Z22normiere_geo_abschnittPP5akopfhdd(void){}
void _Z22schnittbegrenzung_planP5akopfS0_7sbgr_atddd(void){}
void _Z22set_startpunkt_in_xminP5akopfdd(void){}
void _Z23AEP_GenCirElementAmEndeP5akopf10aufmass_rtdidd(void){}
void _Z23AEP_GenLinElementAmEndeP5akopfddhPP6geotecdd(void){}
void _Z23set_innen_aussen_konturP5akopfP6geotecdd(void){}
void _Z23sp_suchstrahl_abschnittdddP5akopfPdS1_hdd(void){}
void _Z24GTDELETE_ElementAmAnfangP5akopf12gt_status_atm(void){}
void _Z24get_eckenart_aus_winkelnddid(void){}
void _Z24schnittbegrenzung_laengsP5akopfS0_7sbgr_atddd(void){}
void _Z25AEP_EndelementVerlaengernP6geotecddd(void){}
void _Z25AEP_GenCirElementAmAnfangP5akopf10aufmass_rtdidd(void){}
void _Z25AEP_SetKonturAnfangsPunktP5akopfmm(void){}
void _Z25AEQ_CloseEintauchbereicheP5akopfddd(void){}
void _Z25AEQ_OptimiereOffeneKonturPP5akopfmiddd(void){}
void _Z25aufloes_form_in_abschnittP5akopf(void){}
void _Z25insert_akopf_on_top_levelP5akopf(void){}
void _Z26chk_punkt_innerhalb_konturP5akopfddPhdd(void){}
void _Z27AEP_StartelementVerlaengernP6geotecddd(void){}
void _Z27AEP_xmax_element_in_bereichP6geotecS0_dd(void){}
void _Z27delete_bearbeitungsmerkmaleP5akopfd(void){}
void _Z27konturdrehsinn_in_abschnittP5akopfdd(void){}
void _Z29AEP_ChkKnotenpunktInAbschnittP5akopfdd(void){}
void _Z29chk_kontur_ausserhalb_rohteilP5akopfS0_Phdd(void){}
void _Z29insert_lower_level_hierarchieP5akopfS0_(void){}
void _Z30FFLIB_GenRechteckAusEckpunkten7plan_at9gruppe_atddddPP5akopfdd(void){}
void _Z30GTFIND_BereichKennungImCalstatP5akopfmPP6geotecS3_(void){}
void _Z30unterteile_kreise_in_abschnittP5akopfdd(void){}
void _Z33AEP_SetInnenAussenStirnRueckseiteP5akopfdd(void){}
void _Z33UEBEROH_store_rohnach_mittelpunktcP5akopfdd(void){}
void _Z37AEPLIB_loesche_antiparallele_bereicheP5akopfdd(void){}
void _Z38AEQ_OptimiereGeschlosseneAufmassKonturP5akopfchdhbPS0_dd(void){}
void _Z41delete_grenzkontur_ausserhalb_huellkonturP5akopfS0_dd(void){}
void _Z6spechtP6geotecS0_PdS1_S1_S1_dd(void){}
void _Z8CheckGeoP5akopfhdd(void){}
void _Z9AEP_xwertdP6geotecd(void){}
void _Z9AEP_ywertdP6geotecd(void){}
void _Z9new_akopf7plan_at9gruppe_at(void){}
void _ZN6nckern9codecheck12RegistrationC1ENS0_7SegmentESt17basic_string_viewIcSt11char_traitsIcEE(void){}
void _ZN6nckern9codecheck12RegistrationD1Ev(void){}
void abstand_pkt_pkt(void){}
void abstand_ziel_start(void){}
void cir_length(void){}
void compare_winkel(void){}
void element_im_kreis(void){}
void element_length(void){}
void kurzpunkt_kontur(void){}
void lin_length(void){}
void norm_winkel(void){}
void normiere_winkel(void){}
void normiere_winkel_auf_koordinatenachse(void){}
void oeffnungswinkel(void){}
void punkt_auf_kontur(void){}
void punkt_auf_konturbereich(void){}
void punkt_auf_konturelement(void){}
void punkt_auf_math_element(void){}
void punktlage(void){}
void ringschluss(void){}
void sp_cir_cir(void){}
void sp_linw_cir(void){}
void sp_linw_linw(void){}
void steigungswinkel(void){}
void stg_element(void){}
void wert_im_intervall(void){}
void winkel_im_sektor(void){}
void winkelhalbierende(void){}
