/* auto-generated: unversioned UND refs for load-time relocs */
void ERRPLIB_NewSysWarning(void){}
void ERRPLIB_SetFileAndLine(void){}
void ERR_GenNewExternError(void){}
void ERR_GenNewExternWarning(void){}
void ERR_GenNewFatalError(void){}
void ERR_InitErrorStatus(void){}
void GEOLIB_extrema_in_bereich(void){}
void GEOLIB_xmax_in_abschnitt(void){}
void GEOLIB_xmin_in_abschnitt(void){}
void GEOLIB_ymax_in_abschnitt(void){}
void GEOLIB_ymin_in_abschnitt(void){}
void WerkzeugTyp(void){}
void _Z11delete_restP5akopf(void){}
void _Z11new_element9basvar_at(void){}
void _Z12copy_bereichP5akopfP6geotecS2_PS0_d(void){}
void _Z13DeleteBereichP6geotecS0_(void){}
void _Z14GTFIND_KennungP5akopf12gt_status_atm(void){}
void _Z14copy_abschnittP5akopfPS0_d(void){}
void _Z14delete_bereichP5akopfP6geotecS2_(void){}
void _Z14free_kk_recordP15konturkorrektur(void){}
void _Z15konturkorrekturP15konturkorrektur(void){}
void _Z15trans_abschnitt8trans_atP5akopfdddd(void){}
void _Z16GTFIND_IsHorLineP6geotecdd(void){}
void _Z16delete_abschnittP5akopf(void){}
void _Z16invert_abschnittP5akopfd(void){}
void _Z17GTFIND_IsVertLineP6geotecdd(void){}
void _Z20SL_G38_schruppkonturP15konturkorrekturP5akopfS2_ddPS2_(void){}
void _Z20renormiere_abschnittP5akopf6hsr_atidd(void){}
void _Z21AEP_SetBamInnenAussenP5akopfdd(void){}
void _Z21SL_G38_schlichtkonturP15konturkorrekturP5akopfdd(void){}
void _Z21set_konturgewinde_parP16tec_cyckongew_rtP6geotecP15konturkorrektur(void){}
void _Z23aufloes_form_in_bereichP5akopfP6geotecS2_(void){}
void _Z25achsp_setze_konturpointerP15konturkorrekturP11konturliste(void){}
void _Z30aufloes_form_in_bereich_ausserP5akopfP6geotecS2_m(void){}
void _Z33chk_korrektur_fuer_stechwerkzeugeP6geoteci(void){}
void _Z45korrigiere_schlichtkontur_fuer_stechwerkzeugeP5akopfdhdd(void){}
void _ZN6nckern9codecheck12RegistrationC1ENS0_7SegmentESt17basic_string_viewIcSt11char_traitsIcEE(void){}
void _ZN6nckern9codecheck12RegistrationD1Ev(void){}
void _ZN9ProductId16IsTurningProductEv(void){}
void abstand_pkt_pkt(void){}
void deferrorNew(void){}
void normiere_winkel(void){}
void ringschluss(void){}
void steigungswinkel(void){}
