#!/usr/bin/env python3
# extract_tables.py — pull the exact static data tables out of the proprietary
# i386 libEp90_Dintabs.so and emit them as C byte arrays (recomp/dintabs/dintabs_tables.h).
#
# We resolve each table's file offset from the ELF section headers (vaddr -> offset),
# so the bytes are reproduced verbatim — no float-literal round-trip, no guessing.
import struct, sys, os

SO = sys.argv[1] if len(sys.argv) > 1 else \
    os.path.join(os.path.dirname(__file__), "../../work/control/sysroot/heros5/bin/libEp90_Dintabs.so")
OUT = os.path.join(os.path.dirname(__file__), "dintabs_tables.h")

data = open(SO, "rb").read()

# --- minimal ELF32 section-header parse to build vaddr->fileoffset map ---
assert data[:4] == b"\x7fELF" and data[4] == 1, "not ELF32"
e_shoff   = struct.unpack_from("<I", data, 0x20)[0]
e_shentsz = struct.unpack_from("<H", data, 0x2e)[0]
e_shnum   = struct.unpack_from("<H", data, 0x30)[0]
sections = []  # (sh_addr, sh_offset, sh_size)
for i in range(e_shnum):
    base = e_shoff + i * e_shentsz
    sh_addr   = struct.unpack_from("<I", data, base + 0x0c)[0]
    sh_offset = struct.unpack_from("<I", data, base + 0x10)[0]
    sh_size   = struct.unpack_from("<I", data, base + 0x14)[0]
    if sh_addr != 0:
        sections.append((sh_addr, sh_offset, sh_size))

def vaddr_to_off(vaddr):
    for sh_addr, sh_offset, sh_size in sections:
        if sh_addr <= vaddr < sh_addr + sh_size:
            return sh_offset + (vaddr - sh_addr)
    raise ValueError(f"vaddr 0x{vaddr:x} not in any section")

# --- tables to extract: (C name, vaddr, size_bytes) ---
# vaddrs are the LINK addresses from `nm` (file image), not Ghidra's +0x10000 base.
TABLES = [
    # freistich tables (din_freistich_rt entries, 0x30 bytes each)
    ("frei_g_werte",  0x5060, 0x4b0),   # 25 entries
    ("frei_ef_werte", 0x5520, 0x120),   # 6 entries
    ("frei_cd_werte", 0x5640, 0x90),    # 3 entries
    ("frei_ab_werte", 0x56e0, 0xc0),    # 4 entries
    # GetNennd nominal-diameter tables (double[])
    ("NennDIN259",  0x2260, 0xd0),      # case 0x0b  (.rodata)
    ("NennNPSF",    0x5a60, 0x38),      # case 0x13
    ("NennNPSC",    0x5b20, 0x70),      # case 0x12
    ("NennNPTF",    0x5c00, 0x60),      # case 0x11
    ("NennNPT",     0x5d20, 0xc0),      # case 0x10
    ("NennUNEF",    0x5ec0, 0xd8),      # case 0x0f
    ("NennUNF",     0x6080, 0xc8),      # case 0x0e
    ("NennUNC",     0x6280, 0x108),     # case 0x0d
    ("NennDIN11",   0x6440, 0xa0),      # case 0x09
    ("NennDIN2999", 0x6560, 0x78),      # case 0x0a
]

# --- scalar constants (doubles, confirmed via disassembly `fld qword`) ---
CONSTS = [
    ("DAT_freistich_tol", 0x20f8, 8),   # freistich ab/cd tolerance
    ("DAT_nenndtbl_eps",  0x2100, 8),   # NenndTblVgl comparison epsilon
]

def emit_bytes(f, name, blob):
    f.write(f"static const unsigned char {name}[{len(blob)}] = {{\n")
    for i in range(0, len(blob), 12):
        row = ", ".join(f"0x{b:02x}" for b in blob[i:i+12])
        f.write(f"    {row},\n")
    f.write("};\n\n")

with open(OUT, "w") as f:
    f.write("/* dintabs_tables.h — AUTO-GENERATED by extract_tables.py.\n")
    f.write(" * Exact static-table bytes lifted from the proprietary i386 libEp90_Dintabs.so.\n")
    f.write(" * Do not edit by hand. */\n#ifndef DINTABS_TABLES_H\n#define DINTABS_TABLES_H\n\n")
    for name, vaddr, size in TABLES:
        off = vaddr_to_off(vaddr)
        blob = data[off:off+size]
        assert len(blob) == size
        emit_bytes(f, name, blob)
    f.write("/* scalar constants (IEEE-754 little-endian doubles) */\n")
    for name, vaddr, size in CONSTS:
        off = vaddr_to_off(vaddr)
        blob = data[off:off+size]
        val = struct.unpack("<d", blob)[0]
        hexbytes = "".join(f"\\x{b:02x}" for b in blob)
        f.write(f"/* {name} = {val!r}  bytes={hexbytes} */\n")
        f.write(f"static const unsigned char {name}_b[8] = {{ {', '.join(f'0x{b:02x}' for b in blob)} }};\n")
        f.write(f"#define {name} (*(const double*){name}_b)\n\n")
    f.write("#endif\n")

print(f"wrote {OUT}")
for name, vaddr, size in TABLES:
    print(f"  {name:14s} vaddr=0x{vaddr:05x} off=0x{vaddr_to_off(vaddr):05x} size={size}")
for name, vaddr, size in CONSTS:
    off = vaddr_to_off(vaddr)
    print(f"  {name:18s} = {struct.unpack('<d', data[off:off+8])[0]}")
